# Generated by Django 5.0.6 on 2024-07-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='connection_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_chop_app.client'),
        ),
    ]
