# Generated by Django 5.0.6 on 2024-07-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chop_app', '0003_alter_client_data_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='connection_product',
        ),
        migrations.AddField(
            model_name='order',
            name='connection_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_chop_app.product'),
        ),
    ]
