# Generated by Django 5.0.6 on 2024-07-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_chop_app', '0004_remove_order_connection_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
