# Generated by Django 5.0.6 on 2024-07-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_chop_app', '0007_image_alter_product_product_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
